### ISSUE TITLE
Problem with unicode

### ISSUE THREAD

**Issue by RamTararam** [Igorjan94/codeforces.vim#1]
vim.current.buffer.append(some_unicode_string) causes 'bad argument type for built-in operation' exception
vim.current.buffer.append(some_unicode_string.encode('utf-8')) fixes the problem for me

VIM version 7.3 under Mac OS X 10.10.2, python 2.7

**Comment by Igorjan94** [comment]
try to update it now, I think I added ".encode('utf-8')" to all buffer.append

**Comment by RamTararam** [comment]
CodeForces#CodeForcesLoadTask
AttributeError: 'list' object has no attribute 'encode'

**Comment by Igorjan94** [comment]
Yep, I found it one minute ago too :)

**Comment by Igorjan94** [comment]
and now?

for i in range(MAGIC):
<TAB>print("I will check all changed functions before commit")

**Comment by RamTararam** [comment]
Now It's OK )
