### ISSUE TITLE
Gives Errors while running :CodeForcesInitServer

### ISSUE THREAD

**Issue by bube5h** [Igorjan94/codeforces.vim#12]
I use WSL.
Steps that I followed:
1. run python server:
![image](https://user-images.githubusercontent.com/34552173/71776195-4c102780-2fb3-11ea-8214-24a8504604d8.png)

2. open vim
3. run :CodeForcesInitServer
gives below errors:
![image](https://user-images.githubusercontent.com/34552173/71776193-37cc2a80-2fb3-11ea-814c-899cba1c66ca.png)

**Comment by Igorjan94** [comment]
Seams that your vim doesn't support python2: check if it supports with vim --version | grep python

**Comment by bube5h** [comment]
Yes.  And I thought just changing 
`python << EOF` to `python3 << EOF` will work.
But that didn't turn out to be working as I was expected.
I think I have to try out this: https://stackoverflow.com/questions/19601729/python-2-support-in-vim
Thank you for responding.
