### ISSUE TITLE
NameError: name 'countSt' is not defined

### ISSUE THREAD

**Issue by ex-surreal** [Igorjan94/codeforces.vim#8]
Error detected while processing function CodeForces#CodeForcesStandings:
line  105:
Traceback (most recent call last):
  File "<string>", line 7, in <module>
NameError: name 'countSt' is not defined

I've faced this error while installing. Things I've done to install:
1. `Plug 'Igorjan94/codeforces.vim'`
2. `pip install requests flask selenium`
3. `brew install chromedriver`
4. Ran `python server.py` on `plugin/`
5. Set cf user name, password and template file

Now, If I run :CodeForcesStandings 700, I get this error. Am I doing something wrong?
PS:
1. I also have `vim-easy-align` installed
2. `echo g:CodeForcesCount` shows `30`

**UPD:** Changing `countSt` to `30` [here](https://github.com/Igorjan94/codeforces.vim/blob/master/autoload/CodeForces.vim#L424) works 

**UPD**: Sorry my bad! missed the `CodeForcesInitServer`. Working now!

**Comment by Igorjan94** [comment]
> UPD: Changing countSt to 30 here works

Sounds strange. Cause it has [default value](https://github.com/Igorjan94/codeforces.vim/blob/master/plugin/codeforces.vim#L38) and shouldn't produce any exceptions..  

you need run CodeForcesInitServer only for submitting, standings should work "from the box" without any settings from you
