### ISSUE TITLE
Can't get it to work ?

### ISSUE THREAD

**Issue by faridtsl** [Igorjan94/codeforces.vim#9]
I started the server but I have this problem.

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', 
port=8200): Max retries exceeded with url: /init_server (Caused by NewConn
ectionError('<requests.packages.urllib3.connection.HTTPConnection object a
t 0x7f76e60c6f10>: Failed to establish a new connection: [Errno 111] Conne
ction refused',))

the server crashes (I have chromium but doesn't work)
is there a way to switch to firefox

**Comment by Igorjan94** [comment]
I'm so sorry for such a long delay, email about issue was in pre-spam folder  
Do you run script with python2?

**Comment by faridtsl** [comment]
yes python2, the first problem was that Vim was not compiled with python2 support, after compiling from source another problem is that it works only with chrome.

**Comment by Igorjan94** [comment]
try to change in [this](https://github.com/Igorjan94/codeforces.vim/blob/master/plugin/server.py#L33) line `Chrome` to `Firefox`. It works for me

**Comment by srikanthmalipatel** [comment]
Even I face the same issue. 
Vim is compiled with python (:echo has('python') returns 1)
unable to figure out. need help. thanks

**Comment by Igorjan94** [comment]
@srikk595 Please, describe your actions step by step how to reproduce this bug

**Comment by srikanthmalipatel** [comment]
These are the steps I followed:
Clone this repo to ~/.vim/bundles/codeforces.vim folder
install python dependencies (requests, HTTPparser, flask, selenium)
Added variables specified in Readme.md to ~/.vimrc
ran :CodeForcesInitServer in vim 

Vim is compiled with python 2.7.13

**Comment by Igorjan94** [comment]
have you run `python2 ~/.vim/bundle/codeforces.vim/plugin/server.py` before `:CodeForcesInitServer`?

**Comment by srikanthmalipatel** [comment]
No. Tried doing that and now I see it working. Thanks.
readme update would help for beginners like me.

**Comment by Igorjan94** [comment]
Yes, I have already updated it to more clear text ;)
